using System.CodeDom.Compiler;
using System.IO;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace DysonCore.DynamicJson.SourceGenerators
{
    [Generator]
    public class PolymorphicSourceGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            
        }

        public void Execute(GeneratorExecutionContext context)
        {
            System.Diagnostics.Debugger.Launch();

            if (context.Compilation.AssemblyName != "DysonCore.DynamicJson.Runtime")
            {
                return;
            }
            
            // var desc = new DiagnosticDescriptor("id", "title", $"[{nameof(PolymorphicSourceGenerator)}] assembly - {context.Compilation.AssemblyName}", "category", DiagnosticSeverity.Error, true);
            // var diag = Diagnostic.Create(desc, Location.None, "random shit");
            // context.ReportDiagnostic(diag);
            
            MemoryStream stream = new MemoryStream();
            StreamWriter writer = new StreamWriter(stream, Encoding.UTF8);
            IndentedTextWriter codeWriter = new IndentedTextWriter(writer);
            
            codeWriter.WriteLine("// <auto-generated>");
            codeWriter.WriteLine($"// This file was generated by a {nameof(PolymorphicSourceGenerator)}.");
            codeWriter.WriteLine("// </auto-generated>");
            
            codeWriter.WriteLine("using System;");
            codeWriter.WriteLine("namespace DysonCore.DynamicJson.CodeGeneration {");
            codeWriter.Indent++;
            
            codeWriter.WriteLine("public static class PolymorphicCacheTest {");
            codeWriter.Indent++;
            
            codeWriter.WriteLine("public static string GetTestText()");
            codeWriter.WriteLine("{");
            codeWriter.Indent++;
            
            codeWriter.WriteLine("return \"Hello, Polymorphic Bitch!\";");
            
            codeWriter.Indent--;
            codeWriter.WriteLine("}");
            
            codeWriter.Indent--;
            codeWriter.WriteLine("}");
            
            codeWriter.Indent--;
            codeWriter.WriteLine("}");
            
            writer.Flush();
            
            context.AddSource("PolymorphicCacheTest.g.cs", SourceText.From(stream, Encoding.UTF8, canBeEmbedded: true));
            
        }
    }
}