#nullable enable
using System;
using System.Text;
using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace DysonCore.DynamicJson.SourceGenerators
{
    [Generator]
    public class SafeStringEnumSourceGenerator : ISourceGenerator
    {

        public void Initialize(GeneratorInitializationContext context)
        {
            //System.Diagnostics.Debugger.Launch(); // Uncomment to debug
            context.RegisterForSyntaxNotifications(() => new EnumSyntaxReceiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            return;
            if (context.Compilation.AssemblyName != "DysonCore.DynamicJson.Runtime")
            {
                return;
            }
            
            // var desc = new DiagnosticDescriptor("id", "title", $"[{nameof(SafeStringEnumSourceGenerator)}] assembly - {context.Compilation.AssemblyName}", "category", DiagnosticSeverity.Error, true);
            // var diag = Diagnostic.Create(desc, Location.None, "random shit");
            // context.ReportDiagnostic(diag);
            
            if (context.SyntaxReceiver is not EnumSyntaxReceiver receiver)
            {
                return;
            }
                

            Compilation compilation = context.Compilation;
            INamedTypeSymbol? enumAttribute = compilation.GetTypeByMetadataName("DefaultEnumValueAttribute");
            
            if (enumAttribute == null)
            {
                // No attribute defined; nothing to generate.
                return;
            }

            // List of mapping entries.
            List<EnumMappingEntry> entries = new ();

            // Process each candidate enum declaration.
            foreach (EnumDeclarationSyntax enumDeclaration in receiver.CandidateEnums)
            {
                SemanticModel model = compilation.GetSemanticModel(enumDeclaration.SyntaxTree);
                
                if (model.GetDeclaredSymbol(enumDeclaration) is not INamedTypeSymbol enumSymbol)
                {
                    continue;
                }

                // Check each enum member for the attribute.
                string? markedMemberName = null;
                
                foreach (var member in enumDeclaration.Members)
                {
                    ISymbol? memberSymbol = model.GetDeclaredSymbol(member);
                    
                    if (memberSymbol == null)
                    {
                        continue;
                    }
                    
                    if (Enumerable.Any(memberSymbol.GetAttributes(), attributeData => SymbolEqualityComparer.Default.Equals(attributeData.AttributeClass, enumAttribute)))
                    {
                        markedMemberName = member.Identifier.Text;
                    }

                    if (markedMemberName != null)
                    {
                        break;
                    }
                }

                if (markedMemberName == null)
                {
                    continue;
                }
                
                bool isPublic = enumSymbol.DeclaredAccessibility == Accessibility.Public;
                string fqName = enumSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                
                if (!fqName.StartsWith("global::"))
                {
                    fqName = "global::" + fqName;
                }

                string assemblyName = enumSymbol.ContainingAssembly.Name;
                // For public enums, we can use typeof; for internal enums, we will use Type.GetType.
                entries.Add(new EnumMappingEntry
                {
                    EnumTypeName = fqName,
                    MarkedMember = markedMemberName,
                    IsPublic = isPublic,
                    AssemblyName = assemblyName
                });
            }

            // Generate the output source.
            StringBuilder sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// This file was generated by DefaultEnumValueGenerator.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("namespace DysonCore.DynamicJson.CodeGeneration");
            sb.AppendLine("{");
            sb.AppendLine("    internal static class DefaultEnumValueCache");
            sb.AppendLine("    {");
            sb.AppendLine(
                "        internal static readonly Dictionary<Type, object> Cache = new Dictionary<Type, object>()");
            sb.AppendLine("        {");

            // For each entry, generate a dictionary entry.
            foreach (var entry in entries)
            {
                if (entry.IsPublic)
                {
                    // Use compile-time typeof and direct enum member access.
                    sb.AppendLine(
                        $"            {{ typeof({entry.EnumTypeName}), {entry.EnumTypeName}.{entry.MarkedMember} }},");
                }
                else
                {
                    // For internal enums, use runtime resolution.
                    // We'll use Type.GetType with the assembly-qualified name.
                    string aqn = $"{entry.EnumTypeName}, {entry.AssemblyName}";
                    sb.AppendLine("            {");
                    sb.AppendLine($"                Type.GetType(\"{Escape(aqn)}\"),");
                    sb.AppendLine("                 Enum.Parse(Type.GetType(\"" + Escape(aqn) + "\"), \"" + entry.MarkedMember + "\")");
                    sb.AppendLine("            },");
                }
            }

            sb.AppendLine("        };");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            Console.WriteLine(sb);
            context.AddSource("DefaultEnumValueCache.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private static string Escape(string input)
        {
            return input.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }

        private struct EnumMappingEntry
        {
            public string EnumTypeName; // Fully qualified name (with global::)
            public string MarkedMember; // The enum member name marked with [DefaultEnumValue]
            public bool IsPublic; // True if the enum is public, false if internal
            public string AssemblyName; // The assembly name where the enum is defined
        }

        private class EnumSyntaxReceiver : ISyntaxReceiver
        {
            public List<EnumDeclarationSyntax> CandidateEnums { get; } = new ();

            public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
            {
                if (syntaxNode is not EnumDeclarationSyntax enumDeclaration)
                {
                    return;
                }
                
                // Look for enum declarations that have at least one attribute on one of their members.
                if (enumDeclaration.Members.Any(member => member.AttributeLists.Count > 0))
                {
                    CandidateEnums.Add(enumDeclaration);
                }
            }
        }
    }
}