#nullable enable

using System.CodeDom.Compiler;
using System.Text;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace DysonCore.DynamicJson.SourceGenerators
{
    [Generator]
    public class SafeStringEnumSourceGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new EnumSyntaxReceiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            if (context.SyntaxReceiver is not EnumSyntaxReceiver receiver)
            {
                return;
            }

            // Check if processed assembly is referencing packages assembly.
            bool isReferenced = context.Compilation.ReferencedAssemblyNames
                .Select(identity => identity.Name == GeneralConstants.PackageAssemblyName)
                .Any();

            // Filter out assemblies which are not referencing package, or if processed assembly is the assembly of the package.
            if (!isReferenced || context.Compilation.AssemblyName == GeneralConstants.PackageAssemblyName)
            {
                return;
            }

            Compilation compilation = context.Compilation;
            INamedTypeSymbol? targetAttribute = compilation.GetTypeByMetadataName(SafeStringEnumConstants.TargetAttributeName);

            if (targetAttribute == null)
            {
                return;
            }

            // List of enums to generate.
            List<EnumEntry> entries = new();
            List<EnumEntry> temporaryEntries = new();

            // Process each candidate enum declaration.
            foreach (EnumDeclarationSyntax enumDeclaration in receiver.CandidateEnums)
            {
                temporaryEntries.Clear();
                SemanticModel model = compilation.GetSemanticModel(enumDeclaration.SyntaxTree);

                if (model.GetDeclaredSymbol(enumDeclaration) is not INamedTypeSymbol enumSymbol)
                {
                    continue;
                }

                foreach (var member in enumDeclaration.Members)
                {
                    ISymbol? memberSymbol = model.GetDeclaredSymbol(member);

                    if (memberSymbol == null 
                        || !memberSymbol.GetAttributes().Any(attributeData => SymbolEqualityComparer.Default.Equals(attributeData.AttributeClass, targetAttribute)))
                    {
                        continue;
                    }
                    
                    temporaryEntries.Add(new EnumEntry(enumSymbol, member.Identifier.Text));
                }

                if (temporaryEntries.Count >= 2)
                {
                    DiagnosticUtils.SendDiagnostics(new DiagnosticDescriptor("SourceGenerator", "Source Generation Error", $"\n[{nameof(SafeStringEnumSourceGenerator)}.{nameof(Execute)}] - {enumSymbol.ToDisplayString()} has more that 1 [{targetAttribute.Name}]. Remove redundant attributes.\n", "category", DiagnosticSeverity.Error, true), context);
                    return;
                }
                
                entries.AddRange(temporaryEntries);
            }

            if (entries.Count <= 0)
            {
                return;
            }

            GenerateSource(entries, context);
        }

        private void GenerateSource(IReadOnlyCollection<EnumEntry> entries, GeneratorExecutionContext context)
        {
            using MemoryStream stream = new MemoryStream();
            using StreamWriter streamWriter = new StreamWriter(stream, Encoding.UTF8);
            IndentedTextWriter writer = new IndentedTextWriter(streamWriter);

            writer.WriteLine("// <auto-generated>");
            writer.WriteLine($"// This file was generated by {nameof(SafeStringEnumSourceGenerator)}.");
            writer.WriteLine($"// It is a part of {GeneralConstants.PackageName} package workflow.");
            writer.WriteLine("// </auto-generated>");
            writer.WriteLine();

            writer.WriteLine("using System;");
            writer.WriteLine("using System.Collections.Generic;");
            writer.WriteLine("using DysonCore.DynamicJson.SafeStringEnumParser;");
            writer.WriteLine("using UnityEngine;");
            writer.WriteLineNoTabs("#if UNITY_EDITOR");
            writer.WriteLine("using UnityEditor;");
            writer.WriteLineNoTabs("#endif");
            writer.WriteLine();

            writer.WriteLine($"namespace {context.Compilation.AssemblyName}.DysonCore.DynamicJson.CodeGeneration");
            writer.WriteLine("{");
            writer.Indent++;

            writer.WriteLine("public static class DefaultEnumValueCache");
            writer.WriteLine("{");
            writer.Indent++;

            writer.WriteLine("private static Dictionary<Type, object> Cache = null;");
            writer.WriteLine();

            // Use both editor and runtime initialization attributes.
            writer.WriteLineNoTabs("#if UNITY_EDITOR");
            writer.WriteLine("[InitializeOnLoadMethod]");
            writer.WriteLineNoTabs("#endif");
            writer.WriteLine("[RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterAssembliesLoaded)]");
            writer.WriteLine("private static void Initialize()");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine($"SafeStringEnumCacheRegistry.Register(\"{context.Compilation.AssemblyName}\", GetCache());");
            writer.Indent--;
            writer.WriteLine("}");
            writer.WriteLine();

            writer.WriteLine("private static Dictionary<Type, object> GetCache()");
            writer.WriteLine("{");
            writer.Indent++;

            writer.WriteLine("if (Cache != null)");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("return Cache;");
            writer.Indent--;
            writer.WriteLine("}");
            writer.WriteLine();

            writer.WriteLine("Dictionary<Type, object> cache = new Dictionary<Type, object>();");
            writer.WriteLine();

            // Generate code for each mapping entry.
            foreach (var entry in entries)
            {
                if (entry.Symbol.DeclaredAccessibility == Accessibility.Private)
                {
                    // For private enums, use runtime resolution:
                    writer.WriteLine("{");
                    writer.Indent++;
                    // Call Type.GetType only once and store in a local variable 'type'.
                    writer.WriteLine($"Type type = Type.GetType(\"{TypeNameUtils.GetAssemblyQualifiedName(entry.Symbol)}\");");
                    writer.WriteLine($"cache.Add(type, Enum.Parse(type, \"{entry.MarkedMemer}\"));");
                    writer.Indent--;
                    writer.WriteLine("}");
                }
                else
                {
                    // For public (or internal) enums, use compile-time typeof and direct member access.
                    string literal = TypeNameUtils.GetCompileTimeLiteral(entry.Symbol);
                    writer.WriteLine($"cache.Add(typeof({literal}), {literal}.{entry.MarkedMemer});");
                }
            }

            writer.WriteLine();
            writer.WriteLine("Cache = cache;");
            writer.WriteLine("return Cache;");
            writer.Indent--;
            writer.WriteLine("}");

            writer.Indent--;
            writer.WriteLine("}");
            writer.Indent--;
            writer.WriteLine("}");

            streamWriter.Flush();
            context.AddSource("DefaultEnumValueCache.g.cs", SourceText.From(stream, Encoding.UTF8, canBeEmbedded: true));
        }
    }
}